### ISSUE TITLE
no go-import meta tags

### ISSUE THREAD

**Issue by RaviTezu** [uber-go/sally#21]
Hi, 

I am not able to get `sally` working on my mac, I think I am missing something here. Any help will be appreciated.

I am running sally using `sally -yml site.yaml` and `site.yaml` has the same content as this repository's README.md, except the url, which points to `<myhost.localdomain.com>` and it said `Starting HTTP handler on ":8080"` when I ran the command. 

On other tab:
``` bash 
[ravi@terminator ~/Go/src/go.uber.org]$curl <myhost.localdomain.com>:8080/grpc
<!DOCTYPE html>
<html>
    <head>
        <meta name="go-import" content="google.golang.org/grpc git https://github.com/grpc/grpc-go">
        <meta name="go-source" content="google.golang.org/grpc https://github.com/grpc/grpc-go https://github.com/grpc/grpc-go/tree/master{/dir} https://github.com/grpc/grpc-go/tree/master{/dir}/{file}#L{line}">
        <meta http-equiv="refresh" content="0; url=https://godoc.org/google.golang.org/grpc">
    </head>
    <body>
        Nothing to see here. Please <a href="https://godoc.org/google.golang.org/grpc">move along</a>.
    </body>
</html>
```

I see the `go-import` meta tag above. But when I do the `go get`, it is failing. See below: 

```bash 
[ravi@terminator ~/Go/src/go.uber.org]$ go get -insecure <myhost.localdomain.com>:8080/grpc
package <myhost.localdomain.com>:8080/grpc: unrecognized import path "<myhost.localdomain.com>" (parse <myhost.localdomain.com>/grpc?go-get=1: no go-import meta tags)
```

Please let me know, If I am doing anything wrong. 
Thanks,
Ravi

**Comment by breerly** [comment]
The Go tool makes request via SSL, so you'll need to have https://myhost.localdomain.com working - my suggestion is to use Cloudflare as your DNS provider so that you can leverage their [free universal SSL](https://www.cloudflare.com/ssl/).

In the coming weeks I'll be working on a guide which details how to easily host your site in Google App Engine with Cloudflare for SSL. We'll also be releasing static site generation so that you can host the site entirely in Github Pages. see #16

**Comment by RaviTezu** [comment]
Awesome. 
Thanks @breerly for the quick response.
